#App configuration
spring.application.name=PayMyBuddy

#Tomcat configuration
server.port=8080

logging.file.name=logs/app.log
logging.file.path=logs

#SQL configuration
spring.datasource.url=jdbc:mysql://localhost:3306/db_paymybuddy?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=rootroot
